name: Build C4 PlantUML
on: [push, create]
jobs:
  generate:
    runs-on: ubuntu-latest
    container: 
      image: structurizr/cli:latest
      volumes:
        - .:/usr/local/structurizr
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Structurizr to PlantUML
        run: /usr/local/structurizr-cli/structurizr.sh export -w docs/workspace.dsl -o output -f plantuml
        working-directory: /usr/local/structurizr

      - uses: actions/upload-artifact@master
        with:
          name: diagrams
          path: |
            **/*.puml

  render:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/download-artifact@master
        with:
          name: diagrams
          path: docs/

      - name: PlantUML GitHub Action
        uses: rotaract/plantuml-action@v1.3.0
        with:
          format: svg
          pattern: 'docs/**/*.puml'

      - uses: actions/upload-artifact@master
        with:
          name: rendered-diagrams
          path: |
            docs/**/*.svg
